name: Deploy to Salesforce (Prod)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Salesforce CLI
        run: |
          npm install --global @salesforce/cli

      - name: Create JWT key file
        run: |
          echo "${{ secrets.JWT_SERVER_KEY }}" > server.key

      - name: Authenticate to Salesforce (JWT)
        run: |
          sf org login jwt \
            --client-id ${{ secrets.CONSUMER_KEY }} \
            --jwt-key-file server.key \
            --username ${{ secrets.DEPLOYMENT_USER_NAME }} \
            --instance-url ${{ secrets.INSTANCE_URL }} \
            --set-default

      - name: Deploy to Salesforce
        run: |
          sf project deploy start \
            --target-org ${{ secrets.DEPLOYMENT_USER_NAME }} \
            --ignore-conflicts
